"""
CLI entry point for compare-prompts.

Provides the `compare-prompts init` command that generates a ready-to-use
test_prompts.py file in the current directory.
"""

import os
import click


TEMPLATE = '''"""
Prompt comparison test file — generated by compare-prompts.

Step-by-Step Guide:
1. Make sure you have your API key set in a `.env` file (e.g., OPENAI_API_KEY=sk-...).
2. Edit "Prompt 1" and "Prompt 2" below to contain the prompts you want to compare.
3. Edit the `inputs` list to include the questions you want to ask both prompts.
4. Set the `model` to the LLM you want to use.
5. Run this file in your terminal: `python test_prompts.py`
6. View the comparison table in your terminal!
"""

from compare_prompts import compare

compare(
    prompts={
        # This is your baseline or original prompt
        "Prompt 1": "You are a helpful assistant.",
        
        # This is the new version of your prompt that you are testing
        "Prompt 2": "You are a concise helpful assistant.",
    },
    inputs=[
        # Add the specific test cases/questions your users will actually ask
        "Explain what a database is.",
        "What is recursion?",
        "Write a short poem about coding.",
    ],
    # Choose your LLM provider. Here are the most common models:
    #   OpenAI:    "gpt-4o-mini" or "gpt-4o"
    #   Anthropic: "claude-haiku-4-5" or "claude-sonnet-4-6"
    #   Gemini:    "gemini/gemini-2.0-flash"
    #   Groq:      "groq/llama-3.3-70b-versatile"  (Free tier available)
    #   Ollama:    "ollama/llama3"                 (Local, completely free)
    #
    # Full list of all 2,600+ supported models: https://models.litellm.ai
    model="gpt-4o-mini",
)
'''


@click.group(invoke_without_command=True)
@click.pass_context
@click.version_option(package_name="compare-prompts")
def main(ctx):
    """compare-prompts — Compare LLM prompts side by side."""
    if ctx.invoked_subcommand is None:
        click.echo(ctx.get_help())


@main.command()
@click.option(
    "--filename",
    default="test_prompts.py",
    help="Name of the file to create (default: test_prompts.py)",
)
def init(filename):
    """Generate a starter test_prompts.py file in the current directory."""
    filepath = os.path.join(os.getcwd(), filename)

    if os.path.exists(filepath):
        click.confirm(
            f"  {filename} already exists. Overwrite?",
            abort=True,
        )

    with open(filepath, "w", encoding="utf-8") as f:
        f.write(TEMPLATE)

    click.echo(f"\n  Created {filename}")
    click.echo(f"  Edit your prompts and inputs in {filename}")
    click.echo(f"  Then run: python {filename}\n")
