"""
CLI entry point for promptdiff.

Provides the `promptdiff init` command that generates a ready-to-use
test_prompts.py file in the current directory.
"""

import os
import click


TEMPLATE = '''"""
Prompt comparison test file — generated by promptdiff.

Edit the prompts and inputs below, then run:
    python test_prompts.py
"""

from promptdiff import compare

compare(
    prompts={
        # Replace these with your actual prompts
        "prompt_a": "You are a helpful assistant.",
        "prompt_b": "You are a concise helpful assistant.",
    },
    inputs=[
        # Replace these with real questions your users ask
        "Explain what a database is.",
        "What is recursion?",
        "Write a short poem about coding.",
    ],
    # Change this to match your LLM provider:
    #   OpenAI:    "gpt-4o-mini" or "gpt-4o"
    #   Anthropic: "claude-haiku-4-5"
    #   Gemini:    "gemini/gemini-2.0-flash"
    #   Groq:      "groq/llama-3.3-70b-versatile"  (free tier)
    #   Ollama:    "ollama/llama3"  (local, free)
    #   Full list: https://models.litellm.ai
    model="gpt-4o-mini",
)
'''


@click.group(invoke_without_command=True)
@click.pass_context
@click.version_option(package_name="promptdiff")
def main(ctx):
    """promptdiff — Compare LLM prompts side by side."""
    if ctx.invoked_subcommand is None:
        click.echo(ctx.get_help())


@main.command()
@click.option(
    "--filename",
    default="test_prompts.py",
    help="Name of the file to create (default: test_prompts.py)",
)
def init(filename):
    """Generate a starter test_prompts.py file in the current directory."""
    filepath = os.path.join(os.getcwd(), filename)

    if os.path.exists(filepath):
        click.confirm(
            f"  {filename} already exists. Overwrite?",
            abort=True,
        )

    with open(filepath, "w", encoding="utf-8") as f:
        f.write(TEMPLATE)

    click.echo(f"\n  Created {filename}")
    click.echo(f"  Edit your prompts and inputs in {filename}")
    click.echo(f"  Then run: python {filename}\n")
